repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        entry: poetry run ruff check --fix
        language: system
        files: \.py$
    -   id: black
        name: black
        entry: poetry run black
        language: system
        files: \.py$
    -   id: mypy
        name: mypy
        entry: poetry run mypy src
        language: system
        files: \.py$
        pass_filenames: false