apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: geometry-service-scaler
  namespace: maliev-dev
spec:
  scaleTargetRef:
    name: maliev-geometry-service
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
  - type: rabbitmq
    metadata:
      queueName: geometry-analysis-queue
      value: "10" # Scale when queue has more than 10 messages
      host: RABBITMQ_URI_SECRET # Injected via secret
